# =======================================================
# Variables
# =======================================================
TOP        ?= pcounter
SRC_DIR    = rtl/
BUILD_DIR  = build/
CONFIG_DIR = configs/
TB_DIR 	   = testbench/
SIMOUT     = simout/
UTILS 	   = utils/

TB_UTILS   = $(abspath $(TB_DIR)/include )
TB_TOP 	   := $(shell find $(abspath $(TB_DIR)src) -type f -iname "tb_$(TOP).cpp" | head -n 1)
TB_SRC     := $(shell find $(TB_DIR)src -type f -name "*.cpp")
PY_SRC     := $(shell find $(UTILS) -type f -name "*.py")

# We need to use different commands to ensure the right order is outputed...
RTL_SRC    := $(shell find $(BUILD_DIR) -type f -name "*.sv")
RTL_SRC    += $(shell find $(SRC_DIR)core -type f -name "*.sv")
RTL_SRC    += $(shell find $(SRC_DIR)peripherals -type f -name "*.sv")
RTL_SRC    += $(SRC_DIR)rv32.sv

MEM_SRC    += $(shell find $(SRC_DIR)memory -type f -name "*.v")

VERILATOR_CFG = verilatorcfg.vlt

# =======================================================
# Parameters and public recipes
# =======================================================
NPROC ?= $(shell nproc)

FILE_LIST = $(BUILD_DIR)sources.f

# --- Verilator options ---
VERILATOR_FLAGS = -Wall \
				  --trace \
				  -j $(NPROC) \
				  --cc $(VERILATOR_CFG) -f $(FILE_LIST) \
				  -O3 \
				  --top-module $(TOP) \
				  --exe $(TB_TOP) $(CCX_UTILS) \
				  -Mdir $(BUILD_DIR) \
				  -I$(BUILD_DIR) \
				  -CFLAGS "-I$(TB_UTILS)"

NEEDED_CONFIS = $(BUILD_DIR)core_config_pkg.svh \
				$(BUILD_DIR)argb_config_pkg.svh \
				$(BUILD_DIR)gpio_config_pkg.svh \
				$(BUILD_DIR)interrupts_config_pkg.svh \
				$(BUILD_DIR)keys_config_pkg.svh \
				$(BUILD_DIR)serial_config_pkg.svh \
				$(BUILD_DIR)timer_config_pkg.svh \
				$(BUILD_DIR)ulpi_config_pkg.svh

NEEDED_ENUMS  = $(BUILD_DIR)/generated_opcodes.svh \
				$(BUILD_DIR)/generated_decoders.svh \
				$(BUILD_DIR)/generated_csr.svh \
				$(BUILD_DIR)/generated_commands.svh


# --- Default target ---
all: run

# Build and run simulation
run: $(BUILD_DIR)/V$(TOP)
	@echo "Running simulation..."
	@$(BUILD_DIR)V$(TOP)

# Compile generated C++ from Verilator
$(BUILD_DIR)/V$(TOP): prepare $(RTL_SRC) $(CXX_TB)  $(TB_TOP)
	verilator $(VERILATOR_FLAGS)
	make -C $(BUILD_DIR) -f V$(TOP).mk V$(TOP) -j8 CXX="ccache g++"

# List the files used for verilator.
$(FILE_LIST) :
	echo "$(MEM_SRC)" | tr ' ' '\n' >> $@
	echo "$(shell find $(BUILD_DIR) -type f -name "*.sv")" | tr ' ' '\n' >> $@
	echo "$(RTL_SRC)" | tr ' ' '\n' >> $@

# Clean
clean:
	rm -rf $(BUILD_DIR)*
	rm -rf $(SIMOUT)*.vcd
	rm -rf logs/*.ans
	rm -rf logs/reports/*.md
	rm -rf logs/reports/*.stat
	rm -rf logs/*.log
	rm -rf documentation/html
	rm -rf documentation/latex
	rm -rf obj_dir/*

tests:
	@python utils/tests.py

wave: run
	@gtkwave $(SIMOUT)$(TOP).vcd

format:
	@verible-verilog-format --inplace --flagfile=.verible-format $(RTL_SRC)
	@clang-format -i --style=file $(TB_SRC)
	@black --line-length 100 $(PY_SRC)

prepare : $(BUILD_DIR) $(BUILD_DIR)generated.h $(FILE_LIST)

.PHONY: all run clean tests doc


# =======================================================
# Autogenerated files : 
# =======================================================
$(BUILD_DIR)generated.h $(BUILD_DIR)generated.sv : $(NEEDED_ENUMS) $(NEEDED_CONFIS)

# =======================================================
# Configuration files : 
# =======================================================

$(BUILD_DIR)core_config_pkg.svh :
	./utils/conf2header.py configs/core/ --output $(BUILD_DIR)
$(BUILD_DIR)argb_config_pkg.svh :
	./utils/conf2header.py configs/peripherals/argb/ --output $(BUILD_DIR)
$(BUILD_DIR)gpio_config_pkg.svh :
	./utils/conf2header.py configs/peripherals/gpio/ --output $(BUILD_DIR)
$(BUILD_DIR)interrupts_config_pkg.svh : 
	./utils/conf2header.py configs/peripherals/interrupts/ --output $(BUILD_DIR)
$(BUILD_DIR)keys_config_pkg.svh :
	./utils/conf2header.py configs/peripherals/keys/ --output $(BUILD_DIR)
$(BUILD_DIR)serial_config_pkg.svh : 
	./utils/conf2header.py configs/peripherals/serial/ --output $(BUILD_DIR)
$(BUILD_DIR)timer_config_pkg.svh :
	./utils/conf2header.py configs/peripherals/timer/ --output $(BUILD_DIR)
$(BUILD_DIR)ulpi_config_pkg.svh :
	./utils/conf2header.py configs/peripherals/ulpi/ --output $(BUILD_DIR)

# =======================================================
# Enums creations
# =======================================================

# Opcodes
$(BUILD_DIR)/generated_opcodes.svh : $(CONFIG_DIR)def/opcodes.def
	./utils/def2header.py -s $(BUILD_DIR)generated_opcodes.svh -c $(BUILD_DIR)generated_opcodes.h $< 

# Decoders
$(BUILD_DIR)/generated_decoders.svh : $(CONFIG_DIR)def/decoders.def
	./utils/def2header.py -s $(BUILD_DIR)generated_decoders.svh -c $(BUILD_DIR)generated_decoders.h $<

# CSRs
$(BUILD_DIR)/generated_csr.svh : $(CONFIG_DIR)def/csr.def
	./utils/def2header.py -s $(BUILD_DIR)generated_csr.svh -c $(BUILD_DIR)generated_csr.h $<

# Commands
$(BUILD_DIR)/generated_commands.svh : $(CONFIG_DIR)def/commands.def
	./utils/def2header.py -s $(BUILD_DIR)generated_commands.svh -c $(BUILD_DIR)generated_commands.h $<

# Build dir
$(BUILD_DIR) : 
	@mkdir $(BUILD_DIR)
