#!/usr/bin/env python3
"""
Generate SystemVerilog and C++ enum definitions from a simple definition file.
"""

import argparse
import re
import sys
import tomllib

def generate_systemverilog(enums, output_path):
    """Generate SystemVerilog package file."""
    lines = [
        "// AUTO-GENERATED FILE - DO NOT EDIT",
        f"// Generated by {__file__.split("/")[-1]}",
        "",
    ]

    for enum in enums:
        # Get explicit bit width or calculate from max value
        explicit_width = extract_bit_width(enum["type"])

        if explicit_width is not None:
            bit_width = explicit_width
            sv_type = enum["type"]
        else:
            # Auto-calculate based on maximum value
            max_value = max(val["value"] for val in enum["values"])
            bit_width = calculate_required_bits(max_value)
            sv_type = f"logic [{bit_width-1}:0]"

        lines.append(f"typedef enum {sv_type} {{")

        for i, val in enumerate(enum["values"]):
            comma = "," if i < len(enum["values"]) - 1 else ""
            sv_val = format_sv_value(val["value"], bit_width)
            lines.append(f"    {val['name']: <20} = {sv_val}{comma}")

        lines.append(f"}} {enum['name']};")
        lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated SystemVerilog: {output_path}")


def generate_cpp(enums, output_path):
    """Generate C++ header file."""
    lines = [
        "// AUTO-GENERATED FILE - DO NOT EDIT",
        f"// Generated by {__file__.split("/")[-1]}",
        "",
        f"#ifndef _{output_path.split("/")[-1].split(".")[0].upper()}_H",
        f"#define _{output_path.split("/")[-1].split(".")[0].upper()}_H",
        "",
        "#include <cstdint>",
        "",
    ]

    for enum in enums:
        # Creating the whole opcode enum
        lines.append(f"typedef enum {{")

        for i, val in enumerate(enum["values"]):
            comma = "," if i < len(enum["values"]) - 1 else ""
            cpp_val = format_cpp_value(val["value"])
            lines.append(f"    {val['name']: <20} = {cpp_val}{comma}")

        lines.append(f"}} {enum['name']};")
        lines.append("")

        # Appending a function to make a lookup-table function
        lines.append(f"static const std::string __{enum['name']}_names[{len(enum["values"])}] = {{")

        for i, val in enumerate(enum["values"]):
            comma = "," if i < len(enum["values"]) - 1 else ""
            lines.append(f"    \"{val['name'][2:]}\"{comma}")
        lines.append("};\n")

        # Appending the function that'll make the lookup
        lines.append(f"inline const std::string get_name({enum["name"]} op)")
        lines.append("{")
        lines.append(f"    return __{enum['name']}_names[static_cast<int>(op)];")
        lines.append("}")

    lines.append(f"\n#endif // _{output_path.split("/")[-1].split(".")[0].upper()}_H")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated C++: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate SystemVerilog and C++ enum definitions from a simple definition file (toml)",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("config_file", help="Input definition file")
    
    parser.add_argument(
        "-s",
        "--systemverilog",
        default="generated_enums.svh",
        metavar="FILE",
        help="SystemVerilog output file (default: generated_enums.svh)",
    )
    parser.add_argument(
        "-c",
        "--cpp",
        default="generated_enums.h",
        metavar="FILE",
        help="C++ output file (default: generated_enums.h)",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")

    args = parser.parse_args()

    try:
        enums = parse_enum_file(args.definition_file)

        if args.verbose:
            print(f"Parsed {len(enums)} enum(s) from {args.definition_file}")
            for enum in enums:
                print(f"  - {enum['name']}: {len(enum['values'])} values")

        generate_systemverilog(enums, args.systemverilog)
        generate_cpp(enums, args.cpp)
        print(f"✓ Successfully generated {len(enums)} enum(s)")

    except FileNotFoundError:
        print(f"Error: File not found: {args.definition_file}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
